"""Preserve task-projection-owned state during exact-13 package registration."""

from __future__ import annotations

import copy
from datetime import datetime
from typing import Any


# `upsert-node.py` owns these values when it projects a task Markdown document.
# They are required by template-contract.json but are not generated by a
# system-dev-planner registration manifest. Registration must therefore retain
# saved values unless the manifest explicitly supplies a replacement.
PROJECTION_OWNED_FIELDS = (
    "purpose", "goal", "scope_in", "scope_out", "acceptance", "architecture_refs",
)


def carry_projection_fields(node: dict[str, Any], saved: Any) -> None:
    """Copy projection-owned values from a saved node when the manifest omits them."""
    if not isinstance(saved, dict):
        return
    for field in PROJECTION_OWNED_FIELDS:
        if field not in node and field in saved:
            node[field] = copy.deepcopy(saved[field])


def _timestamp(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def matches_registered_state(saved: Any, node: dict[str, Any]) -> bool:
    """Accept an unchanged registration when projection only advanced ``updated_at``.

    A missing, unparsable, or regressed timestamp remains a mismatch so callers
    fail closed instead of accepting a potentially stale or altered node.
    """
    if not isinstance(saved, dict):
        return False
    if {key: value for key, value in saved.items() if key != "updated_at"} != {
        key: value for key, value in node.items() if key != "updated_at"
    }:
        return False
    saved_at, node_at = _timestamp(saved.get("updated_at")), _timestamp(node.get("updated_at"))
    if saved_at is None or node_at is None:
        return saved.get("updated_at") == node.get("updated_at")
    return saved_at >= node_at
